name: Build and Published Java SDK

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    environment: publish

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'
          architecture: x64

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.9

      - name: Import GPG Key
        env:
          GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.gnupg
          echo "$GPG_KEY" | gpg --batch --import
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          chmod 700 ~/.gnupg

      - name: Debug GPG Keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Build and Publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn clean deploy --settings .github/config/maven-settings.xml \
            -Dgpg.keyname=${GPG_KEYNAME} \
            -Dgpg.passphrase=${GPG_PASSPHRASE} \
            -Dgpg.executable=gpg \
            -Dgpg.pinentryMode=loopback

      - name: Verify Artifact
        run: |
          ls -l target/yeying-*.jar
