name: Build and Published Java SDK

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'adoptium'
          java-version: '23'
          architecture: x64

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.9 

      - name: Build and Publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn clean deploy --settings .github/config/maven-settings.xml

      - name: Verify Artifact
        run: |
          ls -l target/yeying-sdk-java-1.0.jar